#!/usr/bin/env node
/**
 * Zero-dependency build.
 *
 *   src/content.js     copy and facts
 *   src/sections/*.js  components that render it
 *   src/styles/*.css   design system, concatenated in filename order
 *   src/scripts/*.js   motion engine and behaviours, concatenated in order
 *
 *   →  index.html + assets/site.css + assets/site.js
 *
 * Run: node option-b/build.js
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const out = root;
const assets = join(out, 'assets');

const readDirSorted = async (dir, ext) => {
  const names = (await readdir(dir)).filter((n) => n.endsWith(ext)).sort();
  return Promise.all(names.map(async (n) => ({ name: n, code: await readFile(join(dir, n), 'utf8') })));
};

const banner = (kind) =>
  `/* KiVitronics — Option B. Generated by build.js from src/${kind}. Do not edit directly. */\n`;

/** Conservative CSS minifier: comments and redundant whitespace only. */
const squeezeCss = (css) =>
  css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s*\n\s*/g, '\n')
    .replace(/\n{2,}/g, '\n')
    .trim();

const build = async () => {
  const { homepage } = await import('./src/page.js');
  const { document } = await import('./src/layout.js');

  // assets/ is overwritten, not wiped: og.png is rendered separately by
  // tools/og.mjs and must survive a rebuild.
  await mkdir(assets, { recursive: true });

  const styles = await readDirSorted(join(root, 'src', 'styles'), '.css');
  const css = banner('styles') + squeezeCss(styles.map((s) => s.code).join('\n'));

  const scripts = await readDirSorted(join(root, 'src', 'scripts'), '.js');
  const js = banner('scripts') + scripts.map((s) => s.code).join('\n');

  await writeFile(join(assets, 'site.css'), css);
  await writeFile(join(assets, 'site.js'), js);
  await writeFile(join(assets, 'favicon.svg'), await readFile(join(root, 'src', 'favicon.svg'), 'utf8'));

  const html = document({ body: homepage(), css: 'assets/site.css', js: 'assets/site.js' });
  await writeFile(join(out, 'index.html'), html);

  const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' kB';
  console.log(`built  index.html      ${kb(html)}`);
  console.log(`       assets/site.css ${kb(css)}  (${styles.length} partials)`);
  console.log(`       assets/site.js  ${kb(js)}  (${scripts.length} modules)`);

  const placeholders = (html.match(/data-placeholder/g) || []).length;
  if (placeholders) console.log(`\n${placeholders} unverified placeholder(s) on the page — see src/content.js.`);
};

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
